export const ACTION_ERROR = 'ACTION_ERROR';

// Loading screen
export const END_LOADING = 'END_LOADING';

// API actions
export const RECIEVED_PRINTERS = 'RECIEVED_PRINTERS';
export const RETRIEVING_RESULTS = 'RETRIEVING_RESULTS';
export const RECEIVED_RESULTS = 'RECEIVED_RESULTS';
